version: "3.9"

services:

  rhenus-game-challenge:
    image: cmajid/rhenus-game-challenge
    build:
      context: .
      dockerfile: ./Rhenus/Rhenus.GameChallenge/Dockerfile
    ports:
      - 5500:5500
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5500